<a href="https://colab.research.google.com/github/marianagomez3108-spec/Facturacion/blob/main/S14_pandas_portafolio_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">

# 🐼 S14 — pandas aplicado al portafolio
### Lenguajes de Programación · Ingeniería Financiera

*De columnas sueltas a una tabla que se puede interrogar*

</div>

---

En S13 aprendiste NumPy: arrays, operaciones vectorizadas, funciones de estadística. Hoy conoces **pandas** — la librería que organiza datos de distinto tipo (texto, enteros, decimales) en una sola tabla con nombres.

| Bloque | Tema |
|:---:|---|
| 00 | ¿Qué es pandas y para qué se usa? |
| 01 | La estructura: Series y DataFrame |
| 02 | Cómo se importa pandas |
| 03 | Sintaxis básica: creación y exploración |
| 04 | Selección de datos |
| 05 | Operaciones más usadas |
| 06 | Todo junto: el portafolio como DataFrame |
| 07 | 🎯 Reto individual |

## 00 · ¿Qué es pandas y para qué se usa?

> **Nota** — Objetivo: entender qué problema resuelve pandas, y por qué no basta con lo que ya sabes de NumPy.

Un portafolio real no es solo números: tiene tickers (texto), cantidades (enteros), precios (decimales) y, más adelante, fechas. NumPy asume que todo el array es del mismo tipo — por eso necesitas algo que junte columnas de distinto tipo en una sola tabla, con nombres. Eso es exactamente lo que resuelve **pandas**.

pandas es una librería para trabajar con datos organizados en tablas: leerlos, explorarlos, limpiarlos, filtrarlos y resumirlos. Está construida sobre NumPy — por dentro, cada columna de una tabla de pandas es un array.

> 💡 **Idea clave** — NumPy responde *"¿cómo calculo rápido sobre muchos números?"*. pandas responde *"¿cómo organizo datos de distinto tipo en algo que se pueda leer, filtrar y consultar como una tabla?"*. No compiten — pandas usa NumPy por dentro.

📚 Fuente: ["Package overview", pandas.pydata.org](https://pandas.pydata.org/docs/getting_started/overview.html)

---
## 01 · La estructura: Series y DataFrame

> **Nota** — Objetivo: distinguir las dos estructuras de datos que ofrece pandas.

pandas ofrece dos tipos de estructuras:

- **Series** — un arreglo unidimensional etiquetado, capaz de contener datos de cualquier tipo. Es una sola columna, con índice.
- **DataFrame** — una estructura de dos dimensiones que guarda datos como una tabla, con filas y columnas. Cada columna de un DataFrame es, de hecho, una Series.

In [1]:
import numpy as np
import pandas as pd

precios = pd.Series([195, 385, 185, 165])
print(precios)
print(type(precios))

0    195
1    385
2    185
3    165
dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
portafolio = pd.DataFrame({
    "ticker": ["NVDA", "GOOGL", "META", "TSLA"],
    "cantidad": [9, 5, 5, 10],
    "precio": [279, 338, 329, 479]
})
print(portafolio)
print(type(portafolio))

  ticker  cantidad  precio
0   NVDA         9     279
1  GOOGL         5     338
2   META         5     329
3   TSLA        10     479
<class 'pandas.core.frame.DataFrame'>

📚 Fuente: ["10 minutes to pandas" — "Basic data structures in pandas", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#basic-data-structures-in-pandas)

---
## 02 · Cómo se importa pandas

> **Nota** — Objetivo: importar pandas correctamente, junto con NumPy.

In [11]:
import numpy as np
import pandas as pd

print("pandas", pd.__version__, "listo para usar.")

pandas 2.2.3 listo para usar.

`as pd` es la convención que usa toda la comunidad — casi nunca vas a ver `import pandas` solo, sin el apodo. pandas casi siempre se importa junto con NumPy, porque lo usa por dentro.

---
## 03 · Sintaxis básica: creación y exploración

> **Nota** — Objetivo: crear un DataFrame desde cero y explorarlo antes de calcular nada.

Un DataFrame se crea a partir de un diccionario, donde cada clave se convierte en el nombre de una columna:

In [12]:
portafolio = pd.DataFrame({
    "ticker": ["NVDA", "GOOGL", "META", "TSLA"],
    "cantidad": [9, 5, 5, 10],
    "precio_compra": [317, 280, 266, 496],
    "precio_actual": [279, 338, 329, 479]
})

portafolio

  ticker  cantidad  precio_compra  precio_actual
0   NVDA         9            317            279
1  GOOGL         5            280            338
2   META         5            266            329
3   TSLA        10            496            479

**✏️ Completa el código** — explora el DataFrame antes de calcular nada, igual que hiciste con los precios de Yahoo Finance en S13.

In [13]:
print(portafolio.head())     # primeras filas
print(portafolio.shape)       # (filas, columnas)
print(portafolio.dtypes)       # tipo de cada columna
print(portafolio.describe())     # resumen estadístico

  ticker  cantidad  precio_compra  precio_actual
0   NVDA         9            317            279
1  GOOGL         5            280            338
2   META         5            266            329
3   TSLA        10            496            479
(4, 4)
ticker           object
cantidad          int64
precio_compra     int64
precio_actual     int64
dtype: object
        cantidad  precio_compra  precio_actual
count   4.000000        4.00000        4.00000
mean    7.250000      339.75000      356.25000
std     2.629956      106.36533       85.85016
min     5.000000      266.00000      279.00000
25%     5.000000      276.50000      316.50000
50%     7.000000      298.50000      333.50000
75%     9.250000      361.75000      373.25000
max    10.000000      496.00000      479.00000

<details>
<summary>💡 Ver respuesta</summary>

```python
print(portafolio.head())
print(portafolio.shape)
print(portafolio.dtypes)
print(portafolio.describe())
```
</details>

> 💡 **Idea clave** — `.describe()` no es un método nuevo que memorizar desde cero: junta varias de las funciones que ya conoces de NumPy (`mean`, `std`, `min`, `max`) y te las entrega de una vez, columna por columna.

📚 Fuente: ["10 minutes to pandas" — "Viewing data", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#viewing-data)

---
## 04 · Selección de datos

> **Nota** — Objetivo: extraer columnas, filas y subconjuntos de un DataFrame.

| Sintaxis | Qué selecciona |
|---|---|
| `portafolio["ticker"]` | una sola columna (Series) |
| `portafolio[["ticker", "cantidad"]]` | varias columnas (DataFrame) |
| `portafolio.loc[0]` | una fila, por su etiqueta |
| `portafolio.iloc[0]` | una fila, por su posición |

In [14]:
print(portafolio["ticker"])
print(portafolio.loc[0])

0     NVDA
1    GOOGL
2     META
3     TSLA
Name: ticker, dtype: object
ticker           NVDA
cantidad            9
precio_compra     317
precio_actual     279
Name: 0, dtype: object

**✏️ Completa el código** — filtra el portafolio para quedarte solo con los activos donde `cantidad` sea mayor a 8.

In [15]:
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
muchas_unidades

  ticker  cantidad  precio_compra  precio_actual
0   NVDA         9            317            279
3   TSLA        10            496            479

<details>
<summary>💡 Ver respuesta</summary>

```python
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
```
</details>

> 💡 **Idea clave** — En S13 viste que comparar un array con un número (`ganancia > 0`) devuelve un array de verdadero/falso. Eso es exactamente lo que pasa por dentro cuando filtras un DataFrame: `portafolio["cantidad"] > 8` genera esa misma máscara, y pandas la usa para quedarse solo con las filas donde es verdadera.

📚 Fuente: ["10 minutes to pandas" — "Selection", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#selection)

---
## 05 · Operaciones más usadas

> **Nota** — Objetivo: agregar columnas calculadas y resumir un DataFrame sin ciclos.

Agregar una columna nueva es tan simple como asignarla — pandas alinea los valores automáticamente.

**✏️ Completa el código**

In [16]:
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())   # promedio
print(portafolio["ganancia"].std())   # desviación estándar
portafolio.sort_values(by="ganancia")

23.25
330.1649840105196

  ticker  cantidad  precio_compra  precio_actual  valor_actual  ganancia
0   NVDA         9            317            279          2511      -342
3   TSLA        10            496            479          4790      -170
1  GOOGL         5            280            338          1690       290
2   META         5            266            329          1645       315

<details>
<summary>💡 Ver respuesta</summary>

```python
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())
print(portafolio["ganancia"].std())
portafolio.sort_values(by="ganancia")
```
</details>

| Operación | Qué hace |
|---|---|
| `df["col"] = ...` | crea o reemplaza una columna |
| `df["col"].mean() / .std()` | estadísticas sobre una columna |
| `df.sort_values(by="col")` | ordena las filas según una columna |
| `df[condición]` | filtra filas |

📚 Fuente: ["10 minutes to pandas" — "Operations", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#operations)

---
## 06 · Todo junto: el portafolio como DataFrame

> **Nota** — Objetivo: integrar creación, columnas calculadas, filtro y orden en un solo flujo.

In [17]:
portafolio = pd.DataFrame({
    "ticker": ["NVDA", "GOOGL", "META", "TSLA"],
    "cantidad": [9, 5, 5, 10],
    "precio_compra": [317, 280, 266, 496],
    "precio_actual": [279, 338, 329, 479]
})

portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])
portafolio["rendimiento"] = (portafolio["ganancia"] / (portafolio["cantidad"] * portafolio["precio_compra"])) * 100

en_perdida = portafolio[portafolio["rendimiento"] < 0]
portafolio.sort_values(by="rendimiento", ascending=False)

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
2,META,5,266,329,1645,315,23.684211
1,GOOGL,5,280,338,1690,290,20.714286
3,TSLA,10,496,479,4790,-170,-3.427419
0,NVDA,9,317,279,2511,-342,-11.987382